In [15]:
import numpy as np
k="abc"
while not k.isdigit():
    k=input("Please enter the boardgame size:")
    if k.isdigit():
        k=int(k)
        break
gameboard=np.zeros((k,k))

Please enter the boardgame size: ad
Please enter the boardgame size: 5


In [11]:
def getanswer(x1,x2,turn,k,gameboard):
    x1="abc"
    x2="def"
    while not str(x1).isdigit() and not str(x2).isdigit():
        x1="abc"
        x2="def"
        x1 = input("Player {}, please input vertical location from 0 to {}:".format(turn%2+1,k-1))
        x2 = input("Player {}, please input horizontal location from 0 to {}:".format(turn%2+1,k-1))
        if x1.isdigit() and x2.isdigit():
            x1 = int(x1)
            x2 = int(x2)
            if x1 < 0 or x1 > k or x2 < 0 or x2 > k:
                print("Please input within the range from 0 to {}.".format(k))
                x1="abc"
                x2="def"
                continue
            if gameboard[(x1,x2)]!=0:
                print("Occupied already! Please re-input.")
                x1="abc"
                x2="def"
                continue
        else:
            print("Please input integer from 0 to {}!".format(k))
            continue
    return x1,x2

In [12]:
def putanswer(x1,x2,turn,gameboard):
    if turn%2==0:
        gameboard[x1,x2]=1
    else:
        gameboard[x1,x2]=2
    return gameboard

In [13]:
def checkanswer(x1,x2,k,gameboard):
    a = 0
    b = 0
    c = 0
    d = 0
    e = gameboard[x1,x2]
    for i in range(k):
        if gameboard[x1,x2]==e and gameboard[x1-i,x2]==e:
            a+=1
        elif gameboard[x1,x2]==e and gameboard[x1,x2-i]==e:
            b+=1
        elif x1+x2==k and gameboard[x1,x2]==e and gameboard[x1-k+i-1,x2-1]==e:
            c+=1
        elif x1==x2 and gameboard[x1,x2]==e and gameboard[x1-k+i-1,x2-k+i-1]==e:
            d+=1
    if a==k or b==k or c==k or d==k:
        iswin=True
        return iswin

In [14]:
x1=-1
x2=-1
turn=0
iswin=False
for turn in range(k*k):
    x1,x2=getanswer(x1,x2,turn,k,gameboard)
    gameboard=putanswer(x1,x2,turn,gameboard)
    iswin=checkanswer(x1,x2,k,gameboard)
    print(gameboard)
    if iswin==True:
        print("Player {} is win!".format((turn+1)%2))
        break
if iswin==False:
    print("Draw game!")

Player 1, please input vertical location from 0 to 4: 0
Player 1, please input horizontal location from 0 to 4: 3


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 2, please input vertical location from 0 to 4: 0
Player 2, please input horizontal location from 0 to 4: 0


[[2. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 1, please input vertical location from 0 to 4: 1
Player 1, please input horizontal location from 0 to 4: 3


[[2. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 2, please input vertical location from 0 to 4: 0
Player 2, please input horizontal location from 0 to 4: 1


[[2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 1, please input vertical location from 0 to 4: 2
Player 1, please input horizontal location from 0 to 4: 3


[[2. 2. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 2, please input vertical location from 0 to 4: 0
Player 2, please input horizontal location from 0 to 4: 2


[[2. 2. 2. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Player 1, please input vertical location from 0 to 4: 3
Player 1, please input horizontal location from 0 to 4: 3


[[2. 2. 2. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


Player 2, please input vertical location from 0 to 4: 0
Player 2, please input horizontal location from 0 to 4: 4


[[2. 2. 2. 1. 2.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


Player 1, please input vertical location from 0 to 4: 4
Player 1, please input horizontal location from 0 to 4: 3


[[2. 2. 2. 1. 2.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]
Player 1 is win!
